### PR TITLE
Fixed event listener for uploads

### PR DESCRIPTION
**Pull request by jerridan**
Hi! I noticed that the progress event listener wasn't working for uploads, so I added a new option "uploadEvents". Works just like your "events" option, but instead of:
<code>xhr.addEventListener</code>
it has:
<code>xhr.upload.addEventListener</code>

If there's another way you'd rather fix this issue, go for it. :)

### CODE REVIEW

**Comment by wuct** [comment]
+1, @radiosilence is this PR going to be merged?

**Comment by radiosilence** [comment]
Should be fixed, ta

**Comment by wuct** [comment]
Thanks! I will check it later.

**Comment by bluishoul** [comment]
pls accept this PR

**Pull request closed without merging**
